name: CI
on:
  push:
    branches: [master, next]
  pull_request:
    branches: [master, next]
permissions:
  contents: read
  id-token: write
jobs:
  test:
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.1
      - name: prepare node
        uses: actions/setup-node@v6.1.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: install playwright
        run: npx playwright install --with-deps
      - name: npm install
        run: npm cit
      - name: upload test report
        uses: actions/upload-artifact@v5
        with:
          name: test-report
          path: ${{ github.workspace }}/playwright-report/**/*
          retention-days: 30
        if: ${{ !cancelled() }}
